Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds_ingested = act.io.read_arm_netcdf('/Volumes/T7/data/DL_ingested/crocus-neiu-dlvpt-a1-202308020000.nc')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m ds_ingested [38;5;241m=[39m [43mact[49m[38;5;241;43m.[39;49m[43mio[49m[38;5;241;43m.[39;49m[43mread_arm_netcdf[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m/Volumes/T7/data/DL_ingested/crocus-neiu-dlvpt-a1-202308020000.nc[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/act/io/arm.py:149[0m, in [0;36mread_arm_netcdf[0;34m(filenames, concat_dim, return_None, combine, decode_times, use_cftime, use_base_time, combine_attrs, cleanup_qc, keep_variables, **kwargs)[0m
[1;32m    145[0m     except_tuple [38;5;241m=[39m except_tuple [38;5;241m+[39m ([38;5;167;01mFileNotFoundError[39;00m, [38;5;167;01mOSError[39;00m)
[1;32m    147[0m [38;5;28;01mtry[39;00m:
[1;32m    148[0m     [38;5;66;03m# Read data file with Xarray function[39;00m
[0;32m--> 149[0m     ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_mfdataset[49m[43m([49m[43mfilenames[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    151[0m [38;5;28;01mexcept[39;00m except_tuple [38;5;28;01mas[39;00m exception:
[1;32m    152[0m     [38;5;66;03m# If requested return None for File not found error[39;00m
[1;32m    153[0m     [38;5;28;01mif[39;00m [38;5;28mtype[39m(exception)[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m'[39m[38;5;124mFileNotFoundError[39m[38;5;124m'[39m:

File [0;32m~/miniconda3/envs/instrument-cookbooks-dev/lib/python3.10/site-packages/xarray/backends/api.py:1597[0m, in [0;36mopen_mfdataset[0;34m(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)[0m
[1;32m   1594[0m paths [38;5;241m=[39m _find_absolute_paths(paths, engine[38;5;241m=[39mengine, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1596[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m paths:
[0;32m-> 1597[0m     [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m"[39m[38;5;124mno files to open[39m[38;5;124m"[39m)
[1;32m   1599[0m paths1d: [38;5;28mlist[39m[[38;5;28mstr[39m [38;5;241m|[39m ReadBuffer]
[1;32m   1600[0m [38;5;28;01mif[39;00m combine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mnested[39m[38;5;124m"[39m:

[0;31mOSError[0m: no files to open

